language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

# command to install dependencies
install:
 - pip install .
 - pip install pytest coverage python-coveralls flake8

# command to run tests
script:
  - coverage run --source hms_irc -m py.test
  - flake8 hms_irc

after_success:
 - coveralls
