language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

# command to install dependencies
install:
 - pip install .
 - pip install pytest coverage python-coveralls

# command to run tests
script: coverage run --source hms_irc -m py.test

after_success:
 - coveralls
