from distutils.core import setup
from setuptools import find_packages

from os import path

here = path.abspath(path.dirname(__file__))
with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    long_description = f.read()



setuptools_scm_template = """\
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control

version = '{version}'
"""


setup(
    name='hms_irc',
    use_scm_version={
        'write_to': 'hms_irc/version.py',
        'write_to_template': setuptools_scm_template,
    },
    packages=find_packages(),

    url='https://github.com/haum/hms_irc',
    license='MIT',

    author='Romain Porte (MicroJoe)',
    author_email='microjoe@microjoe.org',

    description='HAUM\'s IRC microservice',
    long_description=long_description,

    classifiers = [
        'Development Status :: 3 - Alpha',

        'Intended Audience :: Developers',

        'Programming Language :: Python :: 3 :: Only',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
    ],

    setup_requires=[
        'setuptools_scm'
    ],

    install_requires=[
        'pika', 'hms_base>=2.0,<3', 'irc', 'coloredlogs',
        'attrs>16,<17'],

    entry_points={
      'console_scripts': [
          'hms_irc = hms_irc.main:main',
          'hms_irc_debug = hms_irc.debug:main',
      ]
    },
)
